name: GreenX CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Project Files
        run: |
          echo "GreenX project checked out successfully"
          ls -la
          git log -1 --oneline

      - name: Check Docker Hub Secrets
        env:
          DOCKER_USERNAME: ${{ secrets.ABDULWASAYKP }}
          DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          test -n "$DOCKER_USERNAME" || exit 1
          test -n "$DOCKER_TOKEN" || exit 1
          echo "Docker Hub secrets are available"

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.ABDULWASAYKP }}
          DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          printf '%s' "$DOCKER_TOKEN" | docker login \
            --username "$DOCKER_USERNAME" \
            --password-stdin

      - name: Build Backend Image
        run: |
          docker build \
            -t abdulwasaykp/greenx-dcs-backend:${{ github.run_number }} \
            ./GreenX_DCS_Assesment_Tool_Backend

      - name: Build Frontend Image
        run: |
          docker build \
            -t abdulwasaykp/greenx-dcs-frontend:${{ github.run_number }} \
            ./greenX-assessment-tool-frontend

      - name: Push Backend Image
        run: |
          docker push \
            abdulwasaykp/greenx-dcs-backend:${{ github.run_number }}

      - name: Push Frontend Image
        run: |
          docker push \
            abdulwasaykp/greenx-dcs-frontend:${{ github.run_number }}

  deploy:
    needs: build-and-deploy
    runs-on: [self-hosted, greenx-vm-156]

    steps:

      - name: Deploy GreenX Application
        env:
          DOCKER_TAG: ${{ github.run_number }}
        run: |
          set -e
          cd /home/osboxes/greenx-deployment

          docker compose \
            --env-file .env \
            -f compose.deploy.yml \
            pull

          docker compose \
            --env-file .env \
            -f compose.deploy.yml \
            up -d

      - name: Verify Deployment
        run: |
          docker ps -a

          docker compose \
            --env-file /home/osboxes/greenx-deployment/.env \
            -f /home/osboxes/greenx-deployment/compose.deploy.yml \
            ps
