name: GreenX CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Project Files
        run: |
          echo "GreenX project checked out successfully"
          ls -la
          echo "Git commit:"
          git log -1 --oneline

      - name: Check Docker Hub Secret
        env:
          DOCKER_USERNAME: ${{ secrets.ABDULWASAYKP }}
          DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "Username length: ${#DOCKER_USERNAME}"
          echo "Token length: ${#DOCKER_TOKEN}"

          if [ -n "$DOCKER_USERNAME" ]; then
            echo "Docker username secret is available"
          else
            echo "Docker username secret is EMPTY"
            exit 1
          fi

          if [ -n "$DOCKER_TOKEN" ]; then
            echo "Docker token secret is available"
          else
            echo "Docker token secret is EMPTY"
            exit 1
          fi

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.ABDULWASAYKP }}
          DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          printf '%s' "$DOCKER_TOKEN" | docker login \
            --username "$DOCKER_USERNAME" \
            --password-stdin

      - name: Build Backend Image
        run: |
          docker build \
            -t abdulwasaykp/greenx-backend:${{ github.run_number }} \
            ./GreenX_DCS_Assesment_Tool_Backend

      - name: Build Frontend Image
        run: |
          docker build \
            -t abdulwasaykp/greenx-frontend:${{ github.run_number }} \
            ./greenX-assessment-tool-frontend

      - name: Show Docker Images
        run: |
          docker images | grep greenx
